---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-env
data:
  POSTGRES_DB: "db"
  POSTGRES_USER: "paperless"
  POSTGRES_PASSWORD: "paperless"  # Achtung: In der Praxis sollten Sie ein Secret für Passwörter verwenden
  POSTGRES_PORT: "5432"
  PGDATA: "/var/lib/postgresql/data/pgdata"
