---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotenberg
  namespace: paperless  # Definiert den spezifischen Namespace für das Deployment
  labels:
    app: gotenberg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotenberg
  template:
    metadata:
      labels:
        app: gotenberg
    spec:
      containers:
      - name: gotenberg
        image: docker.io/gotenberg/gotenberg:latest
        command: ["gotenberg"]
        args: ["--chromium-disable-javascript=true", "--chromium-allow-list=file:///tmp/.*"]
        ports:
        - containerPort: 3000
      restartPolicy: Always  # In Kubernetes, "UnlessStopped" übersetzt zu "Always"
---
apiVersion: v1
kind: Service
metadata:
  name: gotenberg
  namespace: paperless
spec:
  selector:
    app: gotenperg
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
