---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-env
  namespace: paperless
data:
  PAPERLESS_REDIS: redis://broker:6379
  PAPERLESS_DBHOST: db
  PAPERLESS_PORT: "8000"
  PAPERLESS_URL: https://ppl.mathops.info
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      containers:
      - name: paperless
        image: ghcr.io/paperless-ngx/paperless-ngx:latest
        envFrom:
        - configMapRef:
            name: paperless-env
        volumeMounts:
        - name: data-storage
          mountPath: /usr/src/paperless/data
        - name: media-storage
          mountPath: /usr/src/paperless/media
        - name: export-storage
          mountPath: /usr/src/paperless/export
        - name: consume-storage
          mountPath: /usr/src/paperless/consume
        ports:
        - containerPort: 8000
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: paperless-data-claim
      - name: media-storage
        persistentVolumeClaim:
          claimName: paperless-media-claim
      - name: export-storage
        persistentVolumeClaim:
          claimName: paperless-export-claim
      - name: consume-storage
        persistentVolumeClaim:
          claimName: paperless-consume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: paperless
spec:
  selector:
    app: paperless
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000