---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data-claim
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: paperless-data-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-db-claim
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: paperless-db-volume
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: paperless-redis-claim
#   namespace: paperless
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 8Gi
#   storageClassName: longhorn
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: paperless-media-claim
#   namespace: paperless
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 32Gi
#   storageClassName: longhorn
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: paperless-export-claim
#   namespace: paperless
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 8Gi
#   storageClassName: longhorn
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: paperless-consume-claim
#   namespace: paperless
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 8Gi
#   storageClassName: longhorn
