---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: paperless-backend
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: broker-service
spec:
  selector:
    app: paperless-backend
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  selector:
    app: paperless-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000