Kubernetes Konfiguration für Paperless-Umgebung

# tls-secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: paperless-tls-secret
  namespace: paperless
type: kubernetes.io/tls
stringData:
  tls.crt: ${file(tls.crt)}
  tls.key: ${file(tls.key)}
