Kubernetes Konfiguration für Paperless-Umgebung

# tls-secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: paperless-tls-secret
type: kubernetes.io/tls
stringData:
  tls.crt: ${file(../.acme.sh/ppl.mathops.info_ecc/fullchain.cer)}
  tls.key: ${file(../.acme.sh/ppl.mathops.info_ecc/ppl.mathops.info.key)}
